(function(){'use strict';var h=function(a){return!(a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED)};var m=function(a){var c=document.createEvent("Event");c.initEvent("gwdfontsloaded",!0,!0);a.dispatchEvent(c)};var n=function(){};goog.inherits(n,HTMLElement);n.prototype.createdCallback=function(){this.f=[];this.a=null;this.j=this.h.bind(this,!0);this.i=this.h.bind(this,!1);this.b=this.c=null};n.prototype.detachedCallback=function(){p(this)};n.prototype.startDynamicFontLoading=function(){this.a&&(p(this),this.a.parentElement.removeChild(this.a),this.a=null);this.f=[];this.c=null};
n.prototype.parseFontList=function(a){if(void 0!=a){a=a.trim();for(var c="",b=0,e=!1,d=0;d<a.length;d++)if('"'==a[d]&&(e=!e),!(e||","!=a[d]&&d!=a.length-1)){b=a.substring(b,","==a[d]?d:d+1).trim();var f=b.indexOf("https://fonts.googleapis.com/css?family=");if(0==f||1==f){'"'==b[0]&&'"'==b[b.length-1]?this.f.push(b.substring(1,b.length-1)):this.f.push(b);f+=40;var g=b.indexOf(":",f);-1==g&&(g='"'==b[b.length-1]?b.length-1:b.length);b=b.substring(f,g);b=b.length?'"'+b.replace(/[+]/g," ")+'"':""}b&&
(0<c.length&&(c+=", "),c+=b);b=d+1}return c}};
n.prototype.endDynamicFontLoading=function(){var a=this.ownerDocument;if(!a)return!0;for(var c=r(a),b=u(this.f),e=Object.keys(b),d=0;d<e.length;d++){for(var f=e[d],g=b[f],k=c[f]||{},l=Object.keys(g),q=0;q<l.length;q++){var t=l[q];k[t]&&delete g[t]}0==Object.keys(g).length&&delete b[f]}e=Object.keys(b).sort();if(0==e.length)return!0;c="";for(d=0;d<e.length;d++)f=e[d],g=Object.keys(b[f]).sort(),k=g.indexOf("default"),-1!=k&&(0<c.length&&(c+="|"),c+=f,g.splice(k,1)),0<g.length&&(0<c.length&&(c+="|"),
c+=f+":"+g.join(","));this.a=a.createElement("link");this.a.setAttribute("rel","stylesheet");this.a.setAttribute("type","text/css");this.a.setAttribute("href","https://fonts.googleapis.com/css?family="+c);this.ownerDocument.fonts&&this.ownerDocument.fonts.load?(this.c=e.map(function(v){return'"'+v.replace(/[+]/g," ")+'"'}.bind(this)),this.a.addEventListener("load",this.j,!1),this.a.addEventListener("error",this.i,!1)):w(this,e);a.head.insertBefore(this.a,a.head.querySelector("style"));return!1};
var r=function(a){a=Array.prototype.slice.call(a.querySelectorAll('link[href^="https://fonts.googleapis.com/css?family="]')).map(function(c){return c.getAttribute("href")});return u(a)},u=function(a){for(var c={},b=0;b<a.length;b++)for(var e=a[b].substring(40).split("|"),d=0;d<e.length;d++){var f=e[d].indexOf(":"),g=-1==f?e[d]:e[d].substring(0,f),k=c[g]||{};if(-1==f||f==e[d].length-1)k["default"]=!0;else{f=e[d].substring(f+1).split(",");for(var l=0;l<f.length;l++)k[f[l]]=!0}c[g]=k}return c};
n.prototype.h=function(a,c){if(h(this)&&this.a&&c.target==this.a)if(p(this),a&&this.c&&0!=this.c.length){a=this.ownerDocument;c=Array.prototype.slice.call(this.c);for(var b=0;b<c.length;b++){var e=this.l.bind(this,c[b],this.c);a.fonts.load("12px "+c[b]).then(e,e)}}else m(this)};n.prototype.l=function(a,c){c==this.c&&(a=c.indexOf(a),-1!=a&&(c.splice(a,1),0==c.length&&m(this)))};
var w=function(a,c){a.b=[];for(var b=[],e=[],d=0;d<c.length;d++)for(var f=0;2>f;f++){var g=a.ownerDocument.createElement("div");g.className="gwdfontloaderprobe";g.textContent="Sample text";g.style.opacity=0;g.style.position="absolute";g.style.width="auto";g.style.height="auto";g.style.fontFamily='"'+c[d]+'",'+(0==f?"Arial":"Arial Black");a.ownerDocument.body.appendChild(g);a.b.push(g);b.push(g.offsetWidth);e.push(g.offsetHeight)}setTimeout(a.g.bind(a,b,e,0),50)};
n.prototype.g=function(a,c,b){if(h(this)&&this.b&&!this.b.some(function(f){return!h(f)})){for(var e=!0,d=0;d<this.b.length/2;d++)if(this.b[2*d].offsetWidth==a[2*d]&&this.b[2*d].offsetHeight==c[2*d]&&this.b[2*d+1].offsetWidth==a[2*d+1]&&this.b[2*d+1].offsetHeight==c[2*d+1]){e=!1;break}b++;e||40==b?(p(this),m(this)):setTimeout(this.g.bind(this,a,c,b),50)}};
var p=function(a){if(a.ownerDocument.fonts&&a.ownerDocument.fonts.load)a.a&&(a.a.removeEventListener("load",a.j,!1),a.a.removeEventListener("error",a.i,!1));else if(a.b){for(var c=0;c<a.b.length;c++){var b=a.b[c];h(b)&&b.parentElement.removeChild(b)}a.b=null}};document.registerElement("gwd-font-loader",{prototype:n.prototype});}).call(this);
